services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: registry.gitlab.com/redaranj/dev-environment:latest
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

